<<<<<<< HEAD
<<<<<<< HEAD
notify:
  slack:
    url: https://hooks.slack.com/services
    token-path: TTS9Q7GAC/B0519CMM2LV/t7E6fQKOnzUfVfU9cpxdxyEf

=======
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sample
    username: root
    password: root

notify:
  slack:
    url: https://hooks.slack.com/services
    token-path: TTS9Q7GAC/B0519CMM2LV/SliX5SSbn6cM6HGN5latlQGb
>>>>>>> 7659d35 ([jylee] slack 알림 구현 (#11))
=======
notify:
  slack:
    url: https://hooks.slack.com/services
    token-path: TTS9Q7GAC/B0519CMM2LV/t7E6fQKOnzUfVfU9cpxdxyEf
>>>>>>> 6db125b ([jylee] 알림 프로필 변경 및 알림 이력 데이터 저장 구현 (#16))
